// Generated by go-live/shoot/gallery.mjs. Screenshots shown in each project's popup.
export interface Shot {
  src: string;
  label: string;
}

export const SHOTS: Record<string, Shot[]> = {
  "airlock": [
    {
      "src": "/projects/shots/airlock/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/airlock/2.webp",
      "label": "Projects"
    },
    {
      "src": "/projects/shots/airlock/3.webp",
      "label": "Members"
    },
    {
      "src": "/projects/shots/airlock/4.webp",
      "label": "Usage"
    },
    {
      "src": "/projects/shots/airlock/5.webp",
      "label": "Billing"
    }
  ],
  "astra-defi": [
    {
      "src": "/projects/shots/astra-defi/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/astra-defi/2.webp",
      "label": "Demo wallet"
    },
    {
      "src": "/projects/shots/astra-defi/3.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/astra-defi/4.webp",
      "label": "Home, further down"
    }
  ],
  "beat-scope": [
    {
      "src": "/projects/shots/beat-scope/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/beat-scope/2.webp",
      "label": "Analysis"
    }
  ],
  "calldesk": [
    {
      "src": "/projects/shots/calldesk/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/calldesk/2.webp",
      "label": "Recent"
    },
    {
      "src": "/projects/shots/calldesk/3.webp",
      "label": "Users"
    },
    {
      "src": "/projects/shots/calldesk/4.webp",
      "label": "Devices"
    },
    {
      "src": "/projects/shots/calldesk/5.webp",
      "label": "Collapse"
    }
  ],
  "chainscope": [
    {
      "src": "/projects/shots/chainscope/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/chainscope/2.webp",
      "label": "Suppliers"
    },
    {
      "src": "/projects/shots/chainscope/3.webp",
      "label": "Design system"
    }
  ],
  "circuit": [
    {
      "src": "/projects/shots/circuit/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/circuit/2.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/circuit/3.webp",
      "label": "Home, further down"
    }
  ],
  "classquest": [
    {
      "src": "/projects/shots/classquest/1.webp",
      "label": "Teacher"
    },
    {
      "src": "/projects/shots/classquest/2.webp",
      "label": "New assignment"
    }
  ],
  "concourse": [
    {
      "src": "/projects/shots/concourse/1.webp",
      "label": "Flights from LHR to JFK"
    },
    {
      "src": "/projects/shots/concourse/2.webp",
      "label": "Flights from LHR to JFK, further down"
    },
    {
      "src": "/projects/shots/concourse/3.webp",
      "label": "Hotels"
    },
    {
      "src": "/projects/shots/concourse/4.webp",
      "label": "Trips"
    }
  ],
  "contractor": [
    {
      "src": "/projects/shots/contractor/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/contractor/2.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/contractor/3.webp",
      "label": "Proyek"
    },
    {
      "src": "/projects/shots/contractor/4.webp",
      "label": "Layanan"
    },
    {
      "src": "/projects/shots/contractor/5.webp",
      "label": "Tentang"
    }
  ],
  "creator-os": [
    {
      "src": "/projects/shots/creator-os/1.webp",
      "label": "Dashboard"
    },
    {
      "src": "/projects/shots/creator-os/2.webp",
      "label": "Dashboard, further down"
    },
    {
      "src": "/projects/shots/creator-os/3.webp",
      "label": "Creators"
    },
    {
      "src": "/projects/shots/creator-os/4.webp",
      "label": "Deals"
    },
    {
      "src": "/projects/shots/creator-os/5.webp",
      "label": "Inbox"
    }
  ],
  "devfeed": [
    {
      "src": "/projects/shots/devfeed/1.webp",
      "label": "Dashboard"
    },
    {
      "src": "/projects/shots/devfeed/2.webp",
      "label": "Settings"
    },
    {
      "src": "/projects/shots/devfeed/3.webp",
      "label": "Progress"
    }
  ],
  "durian": [
    {
      "src": "/projects/shots/durian/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/durian/2.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/durian/3.webp",
      "label": "Varietas"
    },
    {
      "src": "/projects/shots/durian/4.webp",
      "label": "Cerita kami"
    },
    {
      "src": "/projects/shots/durian/5.webp",
      "label": "Ekspor"
    }
  ],
  "echostream": [
    {
      "src": "/projects/shots/echostream/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/echostream/2.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/echostream/3.webp",
      "label": "About"
    }
  ],
  "familytv": [
    {
      "src": "/projects/shots/familytv/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/familytv/2.webp",
      "label": "Profile mia"
    },
    {
      "src": "/projects/shots/familytv/3.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/familytv/4.webp",
      "label": "Home"
    }
  ],
  "fintrack": [
    {
      "src": "/projects/shots/fintrack/1.webp",
      "label": "Dashboard"
    },
    {
      "src": "/projects/shots/fintrack/2.webp",
      "label": "Markets"
    },
    {
      "src": "/projects/shots/fintrack/3.webp",
      "label": "Calculator"
    },
    {
      "src": "/projects/shots/fintrack/4.webp",
      "label": "Ledger"
    },
    {
      "src": "/projects/shots/fintrack/5.webp",
      "label": "Settings"
    }
  ],
  "frankie-ops": [
    {
      "src": "/projects/shots/frankie-ops/1.webp",
      "label": "Dashboard"
    },
    {
      "src": "/projects/shots/frankie-ops/2.webp",
      "label": "Cases"
    },
    {
      "src": "/projects/shots/frankie-ops/3.webp",
      "label": "Home, further down"
    }
  ],
  "gavel": [
    {
      "src": "/projects/shots/gavel/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/gavel/2.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/gavel/3.webp",
      "label": "Home, further down"
    }
  ],
  "grain-archive": [
    {
      "src": "/projects/shots/grain-archive/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/grain-archive/2.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/grain-archive/3.webp",
      "label": "Archive"
    },
    {
      "src": "/projects/shots/grain-archive/4.webp",
      "label": "About"
    }
  ],
  "homefinder": [
    {
      "src": "/projects/shots/homefinder/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/homefinder/2.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/homefinder/3.webp",
      "label": "Properties"
    },
    {
      "src": "/projects/shots/homefinder/4.webp",
      "label": "Seller"
    },
    {
      "src": "/projects/shots/homefinder/5.webp",
      "label": "Shoutouts"
    }
  ],
  "kanso": [
    {
      "src": "/projects/shots/kanso/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/kanso/2.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/kanso/3.webp",
      "label": "Catalog"
    },
    {
      "src": "/projects/shots/kanso/4.webp",
      "label": "Trade"
    },
    {
      "src": "/projects/shots/kanso/5.webp",
      "label": "About"
    }
  ],
  "lastform": [
    {
      "src": "/projects/shots/lastform/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/lastform/2.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/lastform/3.webp",
      "label": "Collections boots"
    },
    {
      "src": "/projects/shots/lastform/4.webp",
      "label": "Collections derbies"
    },
    {
      "src": "/projects/shots/lastform/5.webp",
      "label": "Collections low profile"
    }
  ],
  "loan-portfolio-dashboard": [
    {
      "src": "/projects/shots/loan-portfolio-dashboard/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/loan-portfolio-dashboard/2.webp",
      "label": "Dark mode"
    },
    {
      "src": "/projects/shots/loan-portfolio-dashboard/3.webp",
      "label": "Sorted amount"
    },
    {
      "src": "/projects/shots/loan-portfolio-dashboard/4.webp",
      "label": "Page"
    }
  ],
  "lumo-demo": [
    {
      "src": "/projects/shots/lumo-demo/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/lumo-demo/2.webp",
      "label": "Creators"
    },
    {
      "src": "/projects/shots/lumo-demo/3.webp",
      "label": "Intelligence"
    },
    {
      "src": "/projects/shots/lumo-demo/4.webp",
      "label": "Settings"
    }
  ],
  "matchpulse": [
    {
      "src": "/projects/shots/matchpulse/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/matchpulse/2.webp",
      "label": "Tournaments"
    },
    {
      "src": "/projects/shots/matchpulse/3.webp",
      "label": "Tournament"
    },
    {
      "src": "/projects/shots/matchpulse/4.webp",
      "label": "Match"
    }
  ],
  "media-dashboard": [
    {
      "src": "/projects/shots/media-dashboard/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/media-dashboard/2.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/media-dashboard/3.webp",
      "label": "Home, further down"
    }
  ],
  "ng-finboard": [
    {
      "src": "/projects/shots/ng-finboard/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/ng-finboard/2.webp",
      "label": "Transactions"
    },
    {
      "src": "/projects/shots/ng-finboard/3.webp",
      "label": "Reports"
    },
    {
      "src": "/projects/shots/ng-finboard/4.webp",
      "label": "Settings"
    }
  ],
  "ottodot": [
    {
      "src": "/projects/shots/ottodot/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/ottodot/2.webp",
      "label": "Admin"
    }
  ],
  "overlay": [
    {
      "src": "/projects/shots/overlay/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/overlay/2.webp",
      "label": "Density"
    },
    {
      "src": "/projects/shots/overlay/3.webp",
      "label": "Dwellings"
    },
    {
      "src": "/projects/shots/overlay/4.webp",
      "label": "Approvals"
    }
  ],
  "pairhaus": [
    {
      "src": "/projects/shots/pairhaus/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/pairhaus/2.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/pairhaus/3.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/pairhaus/4.webp",
      "label": "For designers"
    }
  ],
  "payflow": [
    {
      "src": "/projects/shots/payflow/1.webp",
      "label": "Feed"
    },
    {
      "src": "/projects/shots/payflow/2.webp",
      "label": "Analytics"
    },
    {
      "src": "/projects/shots/payflow/3.webp",
      "label": "Settings"
    }
  ],
  "portier": [
    {
      "src": "/projects/shots/portier/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/portier/2.webp",
      "label": "SF"
    },
    {
      "src": "/projects/shots/portier/3.webp",
      "label": "HS"
    },
    {
      "src": "/projects/shots/portier/4.webp",
      "label": "ZD"
    }
  ],
  "scroll-microsite": [
    {
      "src": "/projects/shots/scroll-microsite/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/scroll-microsite/2.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/scroll-microsite/3.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/scroll-microsite/4.webp",
      "label": "Home, further down"
    }
  ],
  "soundvault": [
    {
      "src": "/projects/shots/soundvault/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/soundvault/2.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/soundvault/3.webp",
      "label": "Sounds"
    },
    {
      "src": "/projects/shots/soundvault/4.webp",
      "label": "Plans"
    },
    {
      "src": "/projects/shots/soundvault/5.webp",
      "label": "Analyze"
    }
  ],
  "sredio-test": [
    {
      "src": "/projects/shots/sredio-test/1.webp",
      "label": "Dashboard"
    },
    {
      "src": "/projects/shots/sredio-test/2.webp",
      "label": "Dashboard, further down"
    },
    {
      "src": "/projects/shots/sredio-test/3.webp",
      "label": "Employees"
    },
    {
      "src": "/projects/shots/sredio-test/4.webp",
      "label": "Profile"
    }
  ],
  "stockflow": [
    {
      "src": "/projects/shots/stockflow/1.webp",
      "label": "Invoices"
    },
    {
      "src": "/projects/shots/stockflow/2.webp",
      "label": "Pending"
    },
    {
      "src": "/projects/shots/stockflow/3.webp",
      "label": "Reviewed"
    },
    {
      "src": "/projects/shots/stockflow/4.webp",
      "label": "Committed"
    }
  ],
  "studioruang": [
    {
      "src": "/projects/shots/studioruang/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/studioruang/2.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/studioruang/3.webp",
      "label": "Projects"
    },
    {
      "src": "/projects/shots/studioruang/4.webp",
      "label": "About"
    },
    {
      "src": "/projects/shots/studioruang/5.webp",
      "label": "Services"
    }
  ],
  "talentradar": [
    {
      "src": "/projects/shots/talentradar/1.webp",
      "label": "Dashboard"
    },
    {
      "src": "/projects/shots/talentradar/2.webp",
      "label": "Talent"
    },
    {
      "src": "/projects/shots/talentradar/3.webp",
      "label": "Pipeline"
    },
    {
      "src": "/projects/shots/talentradar/4.webp",
      "label": "Jobs"
    },
    {
      "src": "/projects/shots/talentradar/5.webp",
      "label": "Settings"
    }
  ],
  "tapehouse": [
    {
      "src": "/projects/shots/tapehouse/1.webp",
      "label": "Home"
    }
  ],
  "verifykit": [
    {
      "src": "/projects/shots/verifykit/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/verifykit/2.webp",
      "label": "Try the demo"
    },
    {
      "src": "/projects/shots/verifykit/3.webp",
      "label": "Docs"
    },
    {
      "src": "/projects/shots/verifykit/4.webp",
      "label": "Dark"
    }
  ],
  "vihara": [
    {
      "src": "/projects/shots/vihara/1.webp",
      "label": "Home"
    },
    {
      "src": "/projects/shots/vihara/2.webp",
      "label": "Home, further down"
    },
    {
      "src": "/projects/shots/vihara/3.webp",
      "label": "Vihara"
    },
    {
      "src": "/projects/shots/vihara/4.webp",
      "label": "Acara"
    }
  ],
  "wedding": [
    {
      "src": "/projects/shots/wedding/1.webp",
      "label": "Floorplan"
    },
    {
      "src": "/projects/shots/wedding/2.webp",
      "label": "Zoomed"
    },
    {
      "src": "/projects/shots/wedding/3.webp",
      "label": "Dietary"
    }
  ]
};
